sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ChtAWXuSiQz9VqkqGtN9sq8VIfqoT4f7biont9DzPZdS2XFSWR8t6+6CYTs9dXa3uFnSTyg84bbKppWxKN2XP6c59rkYOeKXjNTI9tpK0xdn61aNVTPmExlx7T+3YMjzQ6+DPqu+Kid6KeVQIMU4yuH3lwCPcoUk2+BQeCUXB6pFEIaFVkLWHaf7OOmzgKi7nhVQbRx19eDcXqhwpQPLyrBPrj9iok+bu1+h01rmfQmIO+/CLBC+t0xw3TLNzSWSXbDtQBsY8MpEme/ZbhQkyk2WEa1r/7jaGmhg7m2sJfy2Qys2j2+RVsy4wc8l9A+hr7OyD8ChLKj7QCnIGxblUrvBGUNmOeU0s1Vvt1Rc06buKcaB4jUHO2ufy0EDiSIfewqXmn4xsDDfTgnW7NTc9GfldC5mW6DFT6BEpaW6us0v/SLkUeLZYBMldFdu+CjQVwH6xlmh39GIVQfIxW/f9TGBW9mejqnR4VTzfZ1CMwb9coRxzVNIjp4om9rvOaBqLoOFliJ1PzBkNVRCY2dWu/ndlP7Svd8xQaeYlJ2s6ZzpW9/doAVj5TyZ7jNBTPrt2Zl7GIlvwPkRCkEVKDau11z7yb4cm05rWxBkQ5e5mFStFdIphuB436ZdjSeBjywqRzeK9PlIyHrN+kBWUbNEXqkJAxoF5Uefr3+rlUrsNsc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Samantha-at-Saratoga_3425
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy